import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:translator/translator.dart';

class LanguageProvider with ChangeNotifier {
  String _languageCode = 'en';
  final _translator = GoogleTranslator();

  bool get isHindi => _languageCode == 'hi';
  bool get isMarathi => _languageCode == 'mr';
  bool get isKannada => _languageCode == 'kn';
  bool get isTelugu => _languageCode == 'te';
  bool get isGujarati => _languageCode == 'gu';
  String get languageCode => _languageCode;

  LanguageProvider() {
    _loadLanguage();
  }

  void _loadLanguage() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    _languageCode = prefs.getString('languageCode') ?? (prefs.getBool('isHindi') == true ? 'hi' : 'en');
    notifyListeners();
  }

  void toggleLanguage() async {
    if (_languageCode == 'en') {
      _languageCode = 'hi';
    } else if (_languageCode == 'hi') {
      _languageCode = 'mr';
    } else if (_languageCode == 'mr') {
      _languageCode = 'kn';
    } else if (_languageCode == 'kn') {
      _languageCode = 'te';
    } else if (_languageCode == 'te') {
      _languageCode = 'gu';
    } else {
      _languageCode = 'en';
    }
    
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString('languageCode', _languageCode);
    // Keep isHindi for legacy if needed by other components not using this provider
    await prefs.setBool('isHindi', _languageCode == 'hi');
    notifyListeners();
  }

  void setLanguage(String code) async {
    _languageCode = code;
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString('languageCode', _languageCode);
    await prefs.setBool('isHindi', _languageCode == 'hi');
    notifyListeners();
  }

  // Translates dynamic text (AI results) using Google Translate
  Future<String> translateDynamic(String text) async {
    if (text.isEmpty) return text;
    
    // Target language: 'hi' for Hindi, 'mr' for Marathi, 'en' for English
    String targetLang = _languageCode;
    
    try {
      var translation = await _translator.translate(text, to: targetLang);
      return translation.text;
    } catch (e) {
      print("Translation error: $e");
      return text; // Fallback to original
    }
  }

  String translate(String englishText) {
    if (_languageCode == 'en') return englishText;
    
    // Simple mock translation map for the app's static texts
    Map<String, Map<String, String>> _allTranslations = {
      'hi': {
        "GreenMind AI": "ग्रीनमाइंड एआई",
        "GreenMind": "ग्रीनमाइंड",
        "AI Detector": "एआई डिटेक्टर",
        "Capture Image": "छवि कैप्चर करें",
        "Analyze": "विश्लेषण करें",
        "Analyze Now": "अभी विश्लेषण करें",
        "Analyze Image": "छवि का विश्लेषण करें",
        "Select from Gallery": "गैलरी से चुनें",
        "Gallery": "गैलरी",
        "Chat": "चैट",
        "Profile": "प्रोफ़ाइल",
        "Home": "होम",
        "History": "इतिहास",
        "Analysis Result": "विश्लेषण परिणाम",
        "Plant": "पौधा",
        "Disease": "बीमारी",
        "Confidence": "आत्मविश्वास",
        "Description": "विवरण",
        "Cause": "कारण",
        "Solution": "समाधान",
        "View Graph": "ग्राफ़ देखें",
        "Download PDF": "पीडीएफ डाउनलोड करें",
        "Context Chat": "संदर्भ चैट",
        "Environmental Insight": "पर्यावरण अंतर्दृष्टि",
        "No image selected": "कोई छवि चयनित नहीं",
        "Welcome Back!": "वापसी पर स्वागत है!",
        "Login to continue": "जारी रखने के लिए लॉगिन करें",
        "Create Account": "खाता बनाएं",
        "Join our green community": "हमारे हरित समुदाय में शामिल हों",
        "Login": "लॉगिन",
        "Logout": "लॉगआउट",
        "Sign Up": "साइन अप करें",
        "Already have an account? Login": "पहले से ही एक खाता है? लॉगिन करें",
        "Don't have an account? Sign Up": "खाता नहीं है? साइन अप करें",
        "Email": "ईमेल",
        "Password": "पासवर्ड",
        "Please fill all fields": "कृपया सभी फ़ील्ड भरें",
        "Registration successful! Please login.": "पंजीकरण सफल! कृपया लॉगिन करें।",
        "Language: English": "भाषा: हिंदी",
        "Language": "भाषा",
        "GreenMind AI is typing...": "ग्रीनमाइंड एआई टाइप कर रहा है...",
        "Ask about this disease...": "इस बीमारी के बारे में पूछें...",
        "Type a message...": "एक संदेश लिखें...",
        "Listening...": "सुन रहा है...",
        "Disease Expert": "रोग विशेषज्ञ",
        "I see you analyzed a": "मैंने देखा कि आपने विश्लेषण किया",
        "with": "के साथ",
        "What specific questions do you have about treating or managing this?": "इस उपचार या प्रबंधन के बारे में आपके पास क्या विशेष प्रश्न हैं?",
        "Weather unavailable": "मौसम अनुपलब्ध",
        "Humidity": "आर्द्रता",
        "Detect Plant Disease": "पौधों के रोग का पता लगाएं",
        "Scan Plant": "पौधे को स्कैन करें",
        "Select an option to proceed": "आगे बढ़ने के लिए एक विकल्प चुनें",
        "Take a Photo": "फोटो लें",
        "Use camera to scan leaf": "पत्ती को स्कैन करने के लिए कैमरे का उपयोग करें",
        "Choose from Gallery": "गैलरी से चुनें",
        "Select an existing photo": "एक मौजूदा फोटो चुनें",
        "Take a picture of the affected leaf to get instant analysis.": "त्वरित विश्लेषण प्राप्त करने के लिए प्रभावित पत्ती की एक तस्वीर लें।",
        "Weather Details": "मौसम का विवरण",
        "Could not load weather data.": "मौसम डेटा लोड नहीं किया जा सका।",
        "Feels Like": "महसूस होता है",
        "General Plant Care": "सामान्य पौधों की देखभाल",
        "Voice Read": "आवाज से पढ़ें",
        "Stop": "रोकें",
        "Scan saved to Gallery": "स्कॅन गॅलरीमध्ये सेव्ह केले",
        "This is not a plant. Please upload a plant image.": "यह एक पौधा नहीं है। कृपया एक पौधे की छवि अपलोड करें।",
        "It's hot and dry. Ensure your plants are watered frequently and consider misting indoor plants.": "गर्मी और सूखा है। सुनिश्चित करें कि आपके पौधों को बार-बार पानी दिया जाए।",
        "Hot and humid conditions favor rapid growth but also fungal diseases. Ensure good airflow.": "गर्म और आर्द्र स्थितियाँ तीव्र वृद्धि का पक्ष लेती हैं लेकिन फंगल रोगों का भी। अच्छी हवा सुनिश्चित करें।",
        "It's getting cold. Reduce watering frequency and protect sensitive plants from frost.": "ठंड हो रही है। पानी देने की आवृत्ति कम करें और संवेदनशील पौधों को पाले से बचाएं।",
        "Conditions are mild. Maintain standard watering and care routines.": "स्थितियाँ सामान्य हैं। मानक पानी और देखभाल दिनचर्या बनाए रखें।",
        "No scans yet": "अभी तक कोई स्कैन नहीं",
        // Weather conditions
        "Clear": "साफ",
        "Clouds": "बादल",
        "Rain": "बारिश",
        "Drizzle": "बूंदाबांदी",
        "Thunderstorm": "आंधी",
        "Snow": "बर्फ",
        "Mist": "धुंध",
        "Smoke": "धुआं",
        "Haze": "धुंध",
        "Dust": "धूल",
        "Fog": "कोहरा",
        "Sand": "रेत",
        "Ash": "राख",
        "Squall": "आंधी",
        "Tornado": "बवंडर",
        "Network error. Check your connection.": "नेटवर्क त्रुटि। अपना कनेक्शन जांचें।",
        "Sorry, I'm having trouble connecting to my brain.": "क्षमा करें, मुझे जुड़ने में समस्या हो रही है।",
      },
      'mr': {
        "GreenMind AI": "ग्रीनमाइंड एआई",
        "GreenMind": "ग्रीनमाइंड",
        "AI Detector": "एआय डिटेक्टर",
        "Capture Image": "प्रतिमा टिपका",
        "Analyze": "विश्लेषण करा",
        "Analyze Now": "आत्ता विश्लेषण करा",
        "Analyze Image": "प्रतिमेचे विश्लेषण करा",
        "Select from Gallery": "गॅलरीतून निवडा",
        "Gallery": "गॅलरी",
        "Chat": "चॅट",
        "Profile": "प्रोफाइल",
        "Home": "मुख्यपृष्ठ",
        "History": "इतिहास",
        "Analysis Result": "विश्लेषण निकाल",
        "Plant": "रोप",
        "Disease": "रोग",
        "Confidence": "आत्मविश्वास",
        "Description": "वर्णन",
        "Cause": "कारण",
        "Solution": "उपाय",
        "View Graph": "आलेख पहा",
        "Download PDF": "पीडीएफ डाउनलोड करा",
        "Context Chat": "संदर्भ चॅट",
        "Environmental Insight": "पर्यावरणीय माहिती",
        "No image selected": "कोणतीही प्रतिमा निवडलेली नाही",
        "Welcome Back!": "पुन्हा स्वागत आहे!",
        "Login to continue": "पुढे जाण्यासाठी लॉगिन करा",
        "Create Account": "खाते तयार करा",
        "Join our green community": "आमच्या हरित समुदायात सामील व्हा",
        "Login": "लॉगिन",
        "Logout": "लॉगआउट",
        "Sign Up": "साइन अप करा",
        "Already have an account? Login": "आधीच खाते आहे? लॉगिन करा",
        "Don't have an account? Sign Up": "खाते नाही? साइन अप करा",
        "Email": "ईमेल",
        "Password": "पासवर्ड",
        "Please fill all fields": "कृपया सर्व माहिती भरा",
        "Registration successful! Please login.": "नोंदणी यशस्वी! कृपया लॉगिन करा.",
        "Language: English": "भाषा: मराठी",
        "Language": "भाषा",
        "GreenMind AI is typing...": "ग्रीनमाइंड एआई टाइप करत आहे...",
        "Ask about this disease...": "या रोगाबद्दल विचारा...",
        "Type a message...": "संदेश टाइप करा...",
        "Listening...": "ऐकत आहे...",
        "Disease Expert": "रोग तज्ञ",
        "I see you analyzed a": "मी पाहिले की तुम्ही विश्लेषण केले",
        "with": "सह",
        "What specific questions do you have about treating or managing this?": "यावर उपचार किंवा व्यवस्थापनाबद्दल तुमचे काय विशेष प्रश्न आहेत?",
        "Weather unavailable": "हवामान उपलब्ध नाही",
        "Humidity": "आर्द्रता",
        "Detect Plant Disease": "वनस्पतींचे रोग ओळखा",
        "Scan Plant": "रोप स्कॅन करा",
        "Select an option to proceed": "पुढे जाण्यासाठी एक पर्याय निवडा",
        "Take a Photo": "फोटो घ्या",
        "Use camera to scan leaf": "पाने स्कॅन करण्यासाठी कॅमेरा वापरा",
        "Choose from Gallery": "गॅलरीतून निवडा",
        "Select an existing photo": "अस्तित्वात असलेला फोटो निवडा",
        "Take a picture of the affected leaf to get instant analysis.": "त्वरित विश्लेषणासाठी बाधित पानाचा फोटो घ्या।",
        "Weather Details": "हवामानाचा तपशील",
        "Could not load weather data.": "हवामान डेटा लोड झाला नाही.",
        "Feels Like": "जाणवते",
        "General Plant Care": "सामान्य वनस्पती काळजी",
        "Voice Read": "आवाजाने वाचा",
        "Stop": "थांबवा",
        "Scan saved to Gallery": "स्कॅन गॅलरीमध्ये सेव्ह केले",
        "This is not a plant. Please upload a plant image.": "हे रोप नाही. कृपया रोपाची प्रतिमा अपलोड करा.",
        "It's hot and dry. Ensure your plants are watered frequently and consider misting indoor plants.": "हवामान उष्ण आणि कोरडे आहे. तुमच्या वनस्पतींना वारंवार पाणी दिल्याची खात्री करा.",
        "Hot and humid conditions favor rapid growth but also fungal diseases. Ensure good airflow.": "उष्ण आणि दमट हवामान जलद वाढीसाठी अनुकूल आहे परंतु बुरशीजन्य रोगांसाठी देखील. खेळती हवा सुनिश्चित करा.",
        "It's getting cold. Reduce watering frequency and protect sensitive plants from frost.": "थंडी वाढत आहे. पाणी देण्याचे प्रमाण कमी करा आणि संवेदनशील वनस्पतींचे थंडीपासून रक्षण करा.",
        "Conditions are mild. Maintain standard watering and care routines.": "हवामान सौम्य आहे. पाणी देण्याची आणि काळजी घेण्याची नेहमीची पद्धत सुरू ठेवा.",
        "No scans yet": "अद्याप कोणतेही स्कॅन नाहीत",
        // Weather conditions
        "Clear": "स्वच्छ",
        "Clouds": "ढग",
        "Rain": "पाऊस",
        "Drizzle": "रिमझिम",
        "Thunderstorm": "वादळ",
        "Snow": "बर्फ",
        "Mist": "धुके",
        "Smoke": "धूर",
        "Haze": "धुके",
        "Dust": "धुळ",
        "Fog": "धुके",
        "Sand": "वाळू",
        "Ash": "राख",
        "Squall": "वादळ",
        "Tornado": "चक्रीवादळ",
        "Network error. Check your connection.": "नेटवर्क त्रुटी. तुमचे कनेक्शन तपासा.",
        "Sorry, I'm having trouble connecting to my brain.": "क्षमस्व, मला कनेक्ट करण्यात अडचण येत आहे.",
      },
      'kn': {
        "GreenMind AI": "ಗ್ರೀನ್‌ಮೈಂಡ್ ಎಐ",
        "GreenMind": "ಗ್ರೀನ್‌ಮೈಂಡ್",
        "AI Detector": "ಎಐ ಡಿಟೆಕ್ಟರ್",
        "Capture Image": "ಚಿತ್ರವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ",
        "Analyze": "ವಿಶ್ಲೇಷಿಸಿ",
        "Analyze Now": "ಈಗಲೇ ವಿಶ್ಲೇಷಿಸಿ",
        "Analyze Image": "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
        "Select from Gallery": "ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ",
        "Gallery": "ಗ್ಯಾಲರಿ",
        "Chat": "ಚಾಟ್",
        "Profile": "ಪ್ರೊಫೈಲ್",
        "Home": "ಮುಖಪುಟ",
        "History": "ಇತಿಹಾಸ",
        "Analysis Result": "ವಿಶ್ಲೇಷಣೆಯ ಫಲಿತಾಂಶ",
        "Plant": "ಸಸ್ಯ",
        "Disease": "ರೋಗ",
        "Confidence": "ವಿಶ್ವಾಸಾರ್ಹತೆ",
        "Description": "ವಿವರಣೆ",
        "Cause": "ಕಾರಣ",
        "Solution": "ಪರಿಹಾರ",
        "View Graph": "ಗ್ರಾಫ್ ವೀಕ್ಷಿಸಿ",
        "Download PDF": "ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        "Context Chat": "ಸಂದರ್ಭ ಚಾಟ್",
        "Environmental Insight": "ಪರಿಸರ ಒಳನೋಟ",
        "No image selected": "ಯಾವುದೇ ಚಿತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ",
        "Welcome Back!": "ಮತ್ತೆ ಸುಸ್ವಾಗತ!",
        "Login to continue": "ಮುಂದುವರಿಯಲು ಲಾಗಿನ್ ಮಾಡಿ",
        "Create Account": "ಖಾತೆ ರಚಿಸಿ",
        "Join our green community": "ನಮ್ಮ ಹಸಿರು ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ",
        "Login": "ಲಾಗಿನ್",
        "Logout": "ಲಾಗ್‌ಔಟ್",
        "Sign Up": "ಸೈನ್ ಅಪ್",
        "Already have an account? Login": "ಖಾತೆ ಈಗಾಗಲೇ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
        "Don't have an account? Sign Up": "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
        "Email": "ಇಮೇಲ್",
        "Password": "ಪಾಸ್‌ವರ್ಡ್",
        "Please fill all fields": "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ",
        "Registration successful! Please login.": "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ! ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.",
        "Language: English": "ಭಾಷೆ: ಕನ್ನಡ",
        "Language": "ಭಾಷೆ",
        "GreenMind AI is typing...": "ಗ್ರೀನ್‌ಮೈಂಡ್ ಎಐ ಟೈಪ್ ಮಾಡುತ್ತಿದೆ...",
        "Ask about this disease...": "ಈ ರೋಗದ ಬಗ್ಗೆ ಕೇಳಿ...",
        "Type a message...": "ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...",
        "Listening...": "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...",
        "Disease Expert": "ರೋಗ ತಜ್ಞರು",
        "I see you analyzed a": "ನೀವು ವಿಶ್ಲೇಷಿಸಿರುವುದನ್ನು ನಾನು ನೋಡಿದೆ",
        "with": "ಜೊತೆಗೆ",
        "What specific questions do you have about treating or managing this?": "ಇದರ ಚಿಕಿತ್ಸೆ ಅಥವಾ ನಿರ್ವಹಣೆಯ ಬಗ್ಗೆ ನೀವು ಯಾವ ನಿರ್ದಿಷ್ಟ ಪ್ರಶ್ನೆಗಳನ್ನು ಹೊಂದಿದ್ದೀರಿ?",
        "Weather unavailable": "ಹವಾಮಾನ ಲಭ್ಯವಿಲ್ಲ",
        "Humidity": "ಆರ್ದ್ರತೆ",
        "Detect Plant Disease": "ಸಸ್ಯದ ರೋಗವನ್ನು ಪತ್ತೆಹಚ್ಚಿ",
        "Scan Plant": "ಸಸ್ಯವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "Select an option to proceed": "ಮುಂದುವರೆಯಲು ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ",
        "Take a Photo": "ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ",
        "Use camera to scan leaf": "ಎಲೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಕ್ಯಾಮೆರಾ ಬಳಸಿ",
        "Choose from Gallery": "ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್કેಮಾಡಿ",
        "Select an existing photo": "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಫೋಟೋವನ್ನು ಆಯ್કેಮಾಡಿ",
        "Take a picture of the affected leaf to get instant analysis.": "ತ್ವರಿತ ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಲು ಪೀಡಿತ ಎಲೆಯ ಚಿತ್ರವನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.",
        "Weather Details": "ಹವಾಮಾನ ವಿವರಗಳು",
        "Could not load weather data.": "ಹವಾಮಾನ ಡೇಟಾವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
        "Feels Like": "ಹೀಗೆ ಅನಿಸುತ್ತದೆ",
        "General Plant Care": "ಸಾಮಾನ್ಯ ಸಸ್ಯದ ಆರೈಕೆ",
        "Voice Read": "ಧ್ವನಿ ಓದುವಿಕೆ",
        "Stop": "ನಿಲ್ಲಿಸಿ",
        "Scan saved to Gallery": "ಸ್ಕ್ಯಾನ್ ಅನ್ನು ಗ್ಯಾಲರಿಗೆ ಉಳಿಸಲಾಗಿದೆ",
        "This is not a plant. Please upload a plant image.": "ಇದು ಸಸ್ಯವಲ್ಲ. ದಯವಿಟ್ಟು ಸಸ್ಯದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "It's hot and dry. Ensure your plants are watered frequently and consider misting indoor plants.": "ಇದು ಬಿಸಿ ಮತ್ತು ಒಣಗಿದ ವಾತಾವರಣವಾಗಿದೆ. ನಿಮ್ಮ ಸಸ್ಯಗಳಿಗೆ ಆಗಾಗ್ಗೆ ನೀರುಣಿಸುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
        "Hot and humid conditions favor rapid growth but also fungal diseases. Ensure good airflow.": "ಬಿಸಿ ಮತ್ತು ಆರ್ದ್ರ ಪರಿಸ್ಥಿತಿಗಳು ತ್ವರಿತ ಬೆಳವಣಿಗೆಯನ್ನು ಬೆಂಬಲಿಸುತ್ತವೆ ಆದರೆ ಶಿಲೀಂಧ್ರ ರೋಗಗಳನ್ನೂ ಸಹ ಉಂಟುಮಾಡಬಹುದು. ಉತ್ತಮ ಗಾಳಿಯ ಪ್ರಸರಣವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
        "It's getting cold. Reduce watering frequency and protect sensitive plants from frost.": "ಚಳಿಯಾಗುತ್ತಿದೆ. ನೀರುಣಿಸುವ ಆವರ್ತನವನ್ನು ಕಡಿಮೆ ಮಾಡಿ ಮತ್ತು ಸೂಕ್ಷ್ಮ ಸಸ್ಯಗಳನ್ನು ಹಿಮದಿಂದ ರಕ್ಷಿಸಿ.",
        "Conditions are mild. Maintain standard watering and care routines.": "ಪರಿಸ್ಥಿತಿಗಳು ಸಾಧಾರಣವಾಗಿವೆ. ಸಾಮಾನ್ಯ ನೀರುಣಿಸುವಿಕೆ ಮತ್ತು ಆರೈಕೆ ಕ್ರಮಗಳನ್ನು ಮುಂದುವರಿಸಿ.",
        "No scans yet": "ಇನ್ನೂ ಯಾವುದೇ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ",
        "Clear": "ಸ್ವಚ್ಛ",
        "Clouds": "ಮೋಡಗಳು",
        "Rain": "ಮಳೆ",
        "Drizzle": "ತುಂತುರು ಮಳೆ",
        "Thunderstorm": "ಗುಡುಗು ಸಹಿತ ಮಳೆ",
        "Snow": "ಹಿಮ",
        "Mist": "ಮಂಜು",
        "Smoke": "ಹೊಗೆ",
        "Haze": "ಮಸುಕು",
        "Dust": "ಧೂಳು",
        "Fog": "ದಟ್ಟ ಮಂಜು",
        "Sand": "ಮರಳು",
        "Ash": "ಬೂದಿ",
        "Squall": "ಬಿರುಗಾಳಿ",
        "Tornado": "ಸುಂಟರಗಾಳಿ",
        "Network error. Check your connection.": "ನೆಟ್‌ವರ್ಕ್ ದೋಷ. ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.",
        "Sorry, I'm having trouble connecting to my brain.": "ಕ್ಷಮಿಸಿ, ನನ್ನ ಮೆದುಳಿಗೆ ಸಂಪರ್ಕಿಸಲು ತೊಂದರೆಯಾಗುತ್ತಿದೆ.",
      },
      'te': {
        "GreenMind AI": "గ్రీన్ మైండ్ ఐ",
        "GreenMind": "గ్రీన్ మైండ్",
        "AI Detector": "ఐ డిటెక్టర్",
        "Capture Image": "చిత్రాన్ని క్యాప్చర్ చేయండి",
        "Analyze": "విశ్లేషించండి",
        "Analyze Now": "ఇప్పుడే విశ్లేషించండి",
        "Analyze Image": "చిత్రాన్ని విశ్లేషించండి",
        "Select from Gallery": "గ్యాలరీ నుండి ఎంచుకోండి",
        "Gallery": "గ్యాలరీ",
        "Chat": "చాట్",
        "Profile": "ప్రొఫైల్",
        "Home": "హోమ్",
        "History": "చరిత్ర",
        "Analysis Result": "విశ్లేషణ ఫలితం",
        "Plant": "మొక్క",
        "Disease": "వ్యాధి",
        "Confidence": "విశ్వసనీయత",
        "Description": "వివరణ",
        "Cause": "కారణం",
        "Solution": "పరిష్కారం",
        "View Graph": "గ్రాఫ్ చూడండి",
        "Download PDF": "PDF డౌన్‌లోడ్ చేయండి",
        "Context Chat": "సందర్భ చాట్",
        "Environmental Insight": "పర్యావరణ అంతర్దృష్టి",
        "No image selected": "ఏ చిత్రం ఎంచుకోలేదు",
        "Welcome Back!": "మళ్లీ స్వాగతం!",
        "Login to continue": "కొనసాగడానికి లాగిన్ అవ్వండి",
        "Create Account": "ఖాతాను సృష్టించండి",
        "Join our green community": "మా హరిత సంఘంలో చేరండి",
        "Login": "లాగిన్",
        "Logout": "లాగౌట్",
        "Sign Up": "సైన్ అప్",
        "Already have an account? Login": "ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి",
        "Don't have an account? Sign Up": "ఖాతా లేదా? సైన్ అప్ చేయండి",
        "Email": "ఇమెయిల్",
        "Password": "పాస్వర్డ్",
        "Please fill all fields": "దయచేసి అన్ని వివరాలను పూరించండి",
        "Registration successful! Please login.": "నమోదు విజయవంతమైంది! దయచేసి లాగిన్ అవ్వండి.",
        "Language: English": "భాష: తెలుగు",
        "Language": "భాష",
        "GreenMind AI is typing...": "గ్రీన్ మైండ్ ఐ టైప్ చేస్తోంది...",
        "Ask about this disease...": "ఈ వ్యాధి గురించి అడగండి...",
        "Type a message...": "సందేశాన్ని టైప్ చేయండి...",
        "Listening...": "వింటోంది...",
        "Disease Expert": "వ్యాధి నిపుణుడు",
        "I see you analyzed a": "మీరు విశ్లేషించడాన్ని నేను చూశాను",
        "with": "తో",
        "What specific questions do you have about treating or managing this?": "దీనికి చికిత్స లేదా నిర్వహణ గురించి మీకు ఏవైనా నిర్దిష్ట ప్రశ్నలు ఉన్నాయా?",
        "Weather unavailable": "వాతావరణం అందుబాటులో లేదు",
        "Humidity": "తేమ",
        "Detect Plant Disease": "మొక్కల వ్యాధిని గుర్తించండి",
        "Scan Plant": "మొక్కను స్కాన్ చేయండి",
        "Select an option to proceed": "కొనసాగడానికి ఒక ఎంపికను ఎంచుకోండి",
        "Take a Photo": "ఫోటో తీయండి",
        "Use camera to scan leaf": "ఆకును స్కాన్ చేయడానికి కెమెరాను ఉపయోగించండి",
        "Choose from Gallery": "గ్యాలరీ నుండి ఎంచుకోండి",
        "Select an existing photo": "ఉన్న ఫోటోను ఎంచుకోండి",
        "Take a picture of the affected leaf to get instant analysis.": "తక్షణ విశ్లేషణను పొందడానికి ప్రభావిత ఆకు చిత్రాన్ని తీసుకోండి.",
        "Weather Details": "వాతావరణ వివరాలు",
        "Could not load weather data.": "వాతావరణ డేటాను లోడ్ చేయడం సాధ్యపడలేదు.",
        "Feels Like": "ఇలా అనిపిస్తోంది",
        "General Plant Care": "సాధారణ మొక్కల సంరక్షణ",
        "Voice Read": "వాయిస్ రీడ్",
        "Stop": "ఆపండి",
        "Scan saved to Gallery": "స్కాన్ గ్యాలరీలో సేవ్ చేయబడింది",
        "This is not a plant. Please upload a plant image.": "ఇది మొక్క కాదు. దయచేసి మొక్క చిత్రాన్ని అప్‌లోడ్ చేయండి.",
        "It's hot and dry. Ensure your plants are watered frequently and consider misting indoor plants.": "వాతావరణం వేడిగా మరియు పొడిగా ఉంది. మీ మొక్కలకు తరచుగా నీరు పెట్టేలా చూసుకోండి.",
        "Hot and humid conditions favor rapid growth but also fungal diseases. Ensure good airflow.": "వేడి మరియు తేమతో కూడిన పరిస్థితులు వేగవంతమైన వృద్ధికి అనుకూలంగా ఉంటాయి కానీ శిలీంధ్ర వ్యాధులకు కూడా దారితీస్తాయి. మంచి గాలి ప్రసరణను నిర్ధారించండి.",
        "It's getting cold. Reduce watering frequency and protect sensitive plants from frost.": "చలి పెరుగుతోంది. నీరు పెట్టే శాతాన్ని తగ్గించండి మరియు సున్నితమైన మొక్కలను మంచు నుండి రక్షించండి.",
        "Conditions are mild. Maintain standard watering and care routines.": "పరిస్థితులు సాధారణంగా ఉన్నాయి. ప్రామాణిక నీరు మరియు సంరక్షణ పద్ధతులను కొనసాగించండి.",
        "No scans yet": "ఇంకా ఎలాంటి స్కాన్‌లు లేవు",
        "Clear": "స్పష్టం",
        "Clouds": "మేఘాలు",
        "Rain": "వర్షం",
        "Drizzle": "చినుకులు",
        "Thunderstorm": "ఉరుములతో కూడిన తుఫాను",
        "Snow": "మంచు",
        "Mist": "పొగమంచు",
        "Smoke": "పొగ",
        "Haze": "మసక",
        "Dust": "ధూళి",
        "Fog": "మంచు తెర",
        "Sand": "ఇసుక",
        "Ash": "బూడిద",
        "Squall": "ఈదురు గాలులు",
        "Tornado": "టోర్నడో",
        "Network error. Check your connection.": "నెట్‌వర్క్ లోపం. మీ కనెక్షన్‌ని తనిఖీ చేయండి.",
        "Sorry, I'm having trouble connecting to my brain.": "క్షమించండి, నా సర్వర్‌తో కనెక్ట్ కావడంలో ఇబ్బందిగా ఉంది.",
      },
      'gu': {
        "GreenMind AI": "ગ્રીનમાઇન્ડ એઆઇ",
        "GreenMind": "ગ્રીનમાઇન્ડ",
        "AI Detector": "એઆઇ ડિટેક્ટર",
        "Capture Image": "ફોટો લો",
        "Analyze": "વિશ્લેષણ કરો",
        "Analyze Now": "હમણાં જ વિશ્લેષણ કરો",
        "Analyze Image": "છબીનું વિશ્લેષણ કરો",
        "Select from Gallery": "ગેલેરીમાંથી પસંદ કરો",
        "Gallery": "ગેલેરી",
        "Chat": "ચેટ",
        "Profile": "પ્રોફાઇલ",
        "Home": "હોમ",
        "History": "ઇતિહાસ",
        "Analysis Result": "વિશ્લેષણ પરિણામ",
        "Plant": "છોડ",
        "Disease": "રોગ",
        "Confidence": "વિશ્વાસાર્હતા",
        "Description": "વર્ણન",
        "Cause": "કારણ",
        "Solution": "ઉકેલ",
        "View Graph": "ગ્રાફ જુઓ",
        "Download PDF": "પીડીએફ ડાઉનલોડ કરો",
        "Context Chat": "સંદર્ભ ચેટ",
        "Environmental Insight": "પર્યાવરણીય આંતરદૃષ્ટિ",
        "No image selected": "કોઈ છબી પસંદ કરેલ નથી",
        "Welcome Back!": "ફરી સ્વાગત છે!",
        "Login to continue": "ચાલુ રાખવા માટે લોગિન કરો",
        "Create Account": "ખાતું બનાવો",
        "Join our green community": "અમારી ગ્રીન કોમ્યુનિટીમાં જોડાઓ",
        "Login": "લોગિન",
        "Logout": "લોગઆઉટ",
        "Sign Up": "સાઇન અપ",
        "Already have an account? Login": "પહેલેથી જ ખાતું છે? લોગિન કરો",
        "Don't have an account? Sign Up": "ખાતું નથી? સાઇન અપ કરો",
        "Email": "ઇમેઇલ",
        "Password": "પાસવર્ડ",
        "Please fill all fields": "કૃપા કરીને બધા ફીલ્ડ્સ ભરો",
        "Registration successful! Please login.": "નોંધણી સફળ! કૃપા કરીને લોગિન કરો.",
        "Language: English": "ભાષા: ગુજરાતી",
        "Language": "ભાષા",
        "GreenMind AI is typing...": "ગ્રીનમાઇન્ડ એઆઇ ટાઇપ કરી રહ્યું છે...",
        "Ask about this disease...": "આ રોગ વિશે પૂછો...",
        "Type a message...": "સંદેશ લખો...",
        "Listening...": "સાંભળી રહ્યું છે...",
        "Disease Expert": "રોગ નિષ્ણાત",
        "I see you analyzed a": "મેં જોયું કે તમે વિશ્લેષણ કર્યું છે",
        "with": "સાથે",
        "What specific questions do you have about treating or managing this?": "આની સારવાર અથવા સંચાલન વિશે તમને કયા વિશિષ્ટ પ્રશ્નો છે?",
        "Weather unavailable": "હવામાન ઉપલબ્ધ નથી",
        "Humidity": "ભેજ",
        "Detect Plant Disease": "છોડના રોગ શોધો",
        "Scan Plant": "છોડ સ્કેન કરો",
        "Select an option to proceed": "આગળ વધવા માટે એક વિકલ્પ પસંદ કરો",
        "Take a Photo": "ફોટો લો",
        "Use camera to scan leaf": "પાંદડાને સ્કેન કરવા માટે કેમેરાનો ઉપયોગ કરો",
        "Choose from Gallery": "ગેલેરીમાંથી પસંદ કરો",
        "Select an existing photo": "હાલનો ફોટો પસંદ કરો",
        "Take a picture of the affected leaf to get instant analysis.": "ત્યારબાદ ત્વરિત વિશ્લેષણ મેળવવા માટે અસરગ્રસ્ત પાંદડાનો ફોટો લો.",
        "Weather Details": "હવામાન વિગતો",
        "Could not load weather data.": "હવામાન ડેટા લોડ કરી શકાયો નથી.",
        "Feels Like": "અનુભવાય છે",
        "General Plant Care": "સામાન્ય છોડની સંભાળ",
        "Voice Read": "અવાજ દ્વારા વાંચો",
        "Stop": "રોકો",
        "Scan saved to Gallery": "સ્કેન ગેલેરીમાં સાચવવામાં આવ્યું",
        "This is not a plant. Please upload a plant image.": "આ છોડ નથી. કૃપા કરીને છોડનો ફોટો અપલોડ કરો.",
        "It's hot and dry. Ensure your plants are watered frequently and consider misting indoor plants.": "હવામાન ગરમ અને સૂકું છે. તમારા છોડને વારંવાર પાણી આપવાનું સુનિશ્ચિત કરો.",
        "Hot and humid conditions favor rapid growth but also fungal diseases. Ensure good airflow.": "ગરમ અને ભેજવાળી સ્થિતિ ઝડપી વૃદ્ધિ માટે અનુકૂળ છે પરંતુ ફૂગના રોગોને પણ પ્રોત્સાહન આપે છે. સારી હવા ઉજાસ સુનિશ્ચિત કરો.",
        "It's getting cold. Reduce watering frequency and protect sensitive plants from frost.": "ઠંડી વધી રહી છે. પાણી આપવાની આવર્તન ઓછી કરો અને સંવેદનશીલ છોડને ઠંડીથી બચાવો.",
        "Conditions are mild. Maintain standard watering and care routines.": "સ્થિતિ સામાન્ય છે. નિયમિત પાણી અને સંભાળની દિનચર્યા જાળવો.",
        "No scans yet": "હજી સુધી કોઈ સ્કેન નથી",
        "Clear": "ચોખ્ખું",
        "Clouds": "વાદળો",
        "Rain": "વરસાદ",
        "Drizzle": "ઝરમર વરસાદ",
        "Thunderstorm": "વાવાઝોડું",
        "Snow": "બરફ",
        "Mist": "ધુમ્મસ",
        "Smoke": "ધૂમાડો",
        "Haze": "ધૂંધળું",
        "Dust": "ધૂળ",
        "Fog": "ગાઢ ધુમ્મસ",
        "Sand": "રેતી",
        "Ash": "રાખ",
        "Squall": "ઝંઝાવાત",
        "Tornado": "ચક્રવાત",
        "Network error. Check your connection.": "અપૂરતું નેટવર્ક કનેક્શન.",
        "Sorry, I'm having trouble connecting to my brain.": "માફ કરશો, મારા મગજ સાથે જોડાવામાં સમસ્યા આવી રહી છે.",
      }
    };


    return _allTranslations[_languageCode]?[englishText] ?? englishText;
  }
}
